{application,master_banker,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,emysql]},
              {mod,{master_banker_app,[]}},
              {env,[]},
              {modules,[crone,master_banker_app,master_banker_sup,
                        master_banker_worker,mnesia_manager,mysql_manager]}]}.
