{application,budget_pacer,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{budget_pacer_app,[]}},
              {env,[]},
              {modules,[budget_pacer_app,budget_pacer_sup,budget_pacer_worker,
                        crone]}]}.
